<?php

namespace Database\Seeders;

use App\Models\JobPosting;
use Illuminate\Database\Seeder;

class JobPostingSeeder extends Seeder
{
    public function run(): void
    {
        $jobs = [
            [
                'job_id' => 'JOB_001',
                'title' => 'Lập Trình Viên PHP/Laravel',
                'recruitment_period_id' => 'RP_001',
                'description' => 'Tham gia phát triển hệ thống nội bộ bằng PHP/Laravel cho các module vận hành doanh nghiệp.',
                'requirements' => 'PHP 8+, Laravel, MySQL, Git, RESTful API',
                'salary_min' => 15000000,
                'salary_max' => 25000000,
                'quantity' => 2,
                'location' => 'Hà Nội',
                'department' => 'Phòng IT',
                'status' => 'filled',
                'deadline' => now()->subDays(60),
                'is_deleted' => false,
            ],
            [
                'job_id' => 'JOB_002',
                'title' => 'Frontend Developer React',
                'recruitment_period_id' => 'RP_001',
                'description' => 'Phát triển giao diện hệ thống tuyển dụng và dashboard quản trị với React.',
                'requirements' => 'React, TypeScript, Tailwind CSS, Redux, Git',
                'salary_min' => 12000000,
                'salary_max' => 20000000,
                'quantity' => 2,
                'location' => 'TP. Hồ Chí Minh',
                'department' => 'Phòng IT',
                'status' => 'closed',
                'deadline' => now()->subDays(55),
                'is_deleted' => false,
            ],
            [
                'job_id' => 'JOB_003',
                'title' => 'Recruitment Officer',
                'recruitment_period_id' => 'RP_001',
                'description' => 'Phụ trách tìm nguồn ứng viên, sàng lọc hồ sơ và phối hợp phỏng vấn tuyển dụng.',
                'requirements' => 'Kinh nghiệm tuyển dụng 1+ năm, giao tiếp tốt, thành thạo Excel',
                'salary_min' => 11000000,
                'salary_max' => 16000000,
                'quantity' => 1,
                'location' => 'Hà Nội',
                'department' => 'Phòng Nhân Sự',
                'status' => 'filled',
                'deadline' => now()->subDays(50),
                'is_deleted' => false,
            ],
            [
                'job_id' => 'JOB_004',
                'title' => 'Kế Toán Viên',
                'recruitment_period_id' => 'RP_001',
                'description' => 'Hạch toán nghiệp vụ kế toán và tổng hợp chứng từ phát sinh hằng ngày.',
                'requirements' => 'Nắm vững nguyên lý kế toán, Excel tốt, ưu tiên biết MISA',
                'salary_min' => 10000000,
                'salary_max' => 16000000,
                'quantity' => 2,
                'location' => 'Hà Nội',
                'department' => 'Phòng Kế Toán',
                'status' => 'closed',
                'deadline' => now()->subDays(45),
                'is_deleted' => false,
            ],
            [
                'job_id' => 'JOB_005',
                'title' => 'Chuyên Viên Digital Marketing',
                'recruitment_period_id' => 'RP_001',
                'description' => 'Triển khai quảng cáo Facebook/Google và theo dõi hiệu quả theo KPI tuần.',
                'requirements' => 'Facebook Ads, Google Ads, GA4, kỹ năng phân tích dữ liệu',
                'salary_min' => 11000000,
                'salary_max' => 18000000,
                'quantity' => 2,
                'location' => 'TP. Hồ Chí Minh',
                'department' => 'Phòng Marketing',
                'status' => 'filled',
                'deadline' => now()->subDays(40),
                'is_deleted' => false,
            ],
            [
                'job_id' => 'JOB_006',
                'title' => 'Content Creator',
                'recruitment_period_id' => 'RP_001',
                'description' => 'Sản xuất nội dung cho fanpage, website và các chiến dịch truyền thông tuyển dụng.',
                'requirements' => 'Viết tốt, tư duy hình ảnh, hiểu cơ bản SEO và social media',
                'salary_min' => 9000000,
                'salary_max' => 14000000,
                'quantity' => 1,
                'location' => 'TP. Hồ Chí Minh',
                'department' => 'Phòng Marketing',
                'status' => 'closed',
                'deadline' => now()->subDays(35),
                'is_deleted' => false,
            ],
            [
                'job_id' => 'JOB_007',
                'title' => 'Full Stack Developer',
                'recruitment_period_id' => 'RP_002',
                'description' => 'Phát triển đồng thời backend và frontend cho các tính năng mới của hệ thống tuyển dụng.',
                'requirements' => 'Laravel, React, MySQL, Redis, Docker',
                'salary_min' => 20000000,
                'salary_max' => 32000000,
                'quantity' => 2,
                'location' => 'Hà Nội',
                'department' => 'Phòng IT',
                'status' => 'active',
                'deadline' => now()->addDays(25),
                'is_deleted' => false,
            ],
            [
                'job_id' => 'JOB_008',
                'title' => 'Nhân Viên Nhân Sự',
                'recruitment_period_id' => 'RP_002',
                'description' => 'Hỗ trợ quản lý hồ sơ, onboarding nhân sự mới và chăm sóc trải nghiệm nhân viên.',
                'requirements' => 'Tốt nghiệp đại học, cẩn thận, giao tiếp nội bộ tốt',
                'salary_min' => 9000000,
                'salary_max' => 13000000,
                'quantity' => 2,
                'location' => 'Hà Nội',
                'department' => 'Phòng Nhân Sự',
                'status' => 'active',
                'deadline' => now()->addDays(20),
                'is_deleted' => false,
            ],
            [
                'job_id' => 'JOB_009',
                'title' => 'Trưởng Phòng Kế Toán',
                'recruitment_period_id' => 'RP_002',
                'description' => 'Quản lý hoạt động kế toán, kiểm soát ngân sách và lập kế hoạch tài chính quý.',
                'requirements' => 'Kinh nghiệm quản lý 5+ năm, nắm chuẩn mực kế toán, tư duy lãnh đạo',
                'salary_min' => 25000000,
                'salary_max' => 40000000,
                'quantity' => 1,
                'location' => 'Hà Nội',
                'department' => 'Phòng Kế Toán',
                'status' => 'active',
                'deadline' => now()->addDays(28),
                'is_deleted' => false,
            ],
            [
                'job_id' => 'JOB_010',
                'title' => 'Chuyên Viên Trade Marketing',
                'recruitment_period_id' => 'RP_002',
                'description' => 'Triển khai chương trình truyền thông tại điểm chạm và phối hợp đội bán hàng.',
                'requirements' => 'Trade marketing, lập kế hoạch sự kiện, phân tích hiệu quả chiến dịch',
                'salary_min' => 12000000,
                'salary_max' => 18000000,
                'quantity' => 1,
                'location' => 'TP. Hồ Chí Minh',
                'department' => 'Phòng Marketing',
                'status' => 'active',
                'deadline' => now()->addDays(24),
                'is_deleted' => false,
            ],
            [
                'job_id' => 'JOB_012',
                'title' => 'Chuyên viên Quan hệ lao động',
                'recruitment_period_id' => 'RP_002',
                'description' => 'Tư vấn chính sách lao động, giải quyết quan hệ lao động và truyền thông nội bộ.',
                'requirements' => 'Hiểu luật lao động, kỹ năng xử lý tình huống, giao tiếp tốt',
                'salary_min' => 10000000,
                'salary_max' => 15000000,
                'quantity' => 1,
                'location' => 'Hà Nội',
                'department' => 'Phòng Nhân Sự',
                'status' => 'active',
                'deadline' => now()->addDays(18),
                'is_deleted' => false,
            ],
            [
                'job_id' => 'JOB_013',
                'title' => 'Data Analyst',
                'recruitment_period_id' => 'RP_003',
                'description' => 'Phân tích dữ liệu tuyển dụng và vận hành để hỗ trợ ra quyết định quản trị.',
                'requirements' => 'SQL, Power BI/Tableau, Excel nâng cao, tư duy phân tích',
                'salary_min' => 15000000,
                'salary_max' => 23000000,
                'quantity' => 1,
                'location' => 'Hà Nội',
                'department' => 'Phòng IT',
                'status' => 'active',
                'deadline' => now()->addDays(90),
                'is_deleted' => false,
            ],
            [
                'job_id' => 'JOB_014',
                'title' => 'QA Engineer',
                'recruitment_period_id' => 'RP_003',
                'description' => 'Thiết kế test case, kiểm thử chức năng và phối hợp fix bug với đội phát triển.',
                'requirements' => 'Manual testing, viết test case, hiểu API testing là lợi thế',
                'salary_min' => 13000000,
                'salary_max' => 20000000,
                'quantity' => 1,
                'location' => 'TP. Hồ Chí Minh',
                'department' => 'Phòng IT',
                'status' => 'active',
                'deadline' => now()->addDays(95),
                'is_deleted' => false,
            ],
            [
                'job_id' => 'JOB_015',
                'title' => 'Chuyên viên Đào tạo nội bộ',
                'recruitment_period_id' => 'RP_003',
                'description' => 'Xây dựng chương trình đào tạo hội nhập và lộ trình phát triển năng lực nhân sự.',
                'requirements' => 'Kỹ năng đào tạo, thiết kế tài liệu, thuyết trình tốt',
                'salary_min' => 11000000,
                'salary_max' => 17000000,
                'quantity' => 1,
                'location' => 'Hà Nội',
                'department' => 'Phòng Nhân Sự',
                'status' => 'active',
                'deadline' => now()->addDays(85),
                'is_deleted' => false,
            ],
            [
                'job_id' => 'JOB_016',
                'title' => 'Kế toán công nợ',
                'recruitment_period_id' => 'RP_003',
                'description' => 'Quản lý công nợ phải thu, phải trả và đối chiếu số liệu với đối tác định kỳ.',
                'requirements' => 'Kế toán công nợ, Excel tốt, cẩn thận và chính xác',
                'salary_min' => 10000000,
                'salary_max' => 15000000,
                'quantity' => 2,
                'location' => 'Đà Nẵng',
                'department' => 'Phòng Kế Toán',
                'status' => 'active',
                'deadline' => now()->addDays(88),
                'is_deleted' => false,
            ],
            [
                'job_id' => 'JOB_019',
                'title' => 'System Administrator',
                'recruitment_period_id' => 'RP_004',
                'description' => 'Quản trị máy chủ nội bộ, phân quyền truy cập và giám sát bảo mật hệ thống.',
                'requirements' => 'Windows/Linux server, networking, bảo mật cơ bản',
                'salary_min' => 14000000,
                'salary_max' => 22000000,
                'quantity' => 1,
                'location' => 'Hà Nội',
                'department' => 'Phòng IT',
                'status' => 'active',
                'deadline' => now()->addDays(170),
                'is_deleted' => false,
            ],
            [
                'job_id' => 'JOB_020',
                'title' => 'Business Analyst',
                'recruitment_period_id' => 'RP_004',
                'description' => 'Phân tích yêu cầu nghiệp vụ và đề xuất giải pháp hệ thống cho khối nhân sự.',
                'requirements' => 'Phân tích nghiệp vụ, viết tài liệu, giao tiếp khách hàng nội bộ',
                'salary_min' => 15000000,
                'salary_max' => 24000000,
                'quantity' => 1,
                'location' => 'TP. Hồ Chí Minh',
                'department' => 'Phòng IT',
                'status' => 'active',
                'deadline' => now()->addDays(175),
                'is_deleted' => false,
            ],
            [
                'job_id' => 'JOB_021',
                'title' => 'Chuyên viên Talent Acquisition',
                'recruitment_period_id' => 'RP_004',
                'description' => 'Mở rộng nguồn ứng viên chiến lược cho các vị trí quản lý và chuyên môn.',
                'requirements' => 'Tuyển dụng mass và headhunt, networking tốt, phỏng vấn hành vi',
                'salary_min' => 12000000,
                'salary_max' => 18000000,
                'quantity' => 1,
                'location' => 'Hà Nội',
                'department' => 'Phòng Nhân Sự',
                'status' => 'active',
                'deadline' => now()->addDays(165),
                'is_deleted' => false,
            ],
            [
                'job_id' => 'JOB_022',
                'title' => 'Kế toán thuế',
                'recruitment_period_id' => 'RP_004',
                'description' => 'Lập tờ khai thuế định kỳ, kiểm soát chứng từ thuế và làm việc với cơ quan thuế.',
                'requirements' => 'Nghiệp vụ kế toán thuế, cẩn thận, cập nhật quy định thuế',
                'salary_min' => 12000000,
                'salary_max' => 19000000,
                'quantity' => 1,
                'location' => 'Đà Nẵng',
                'department' => 'Phòng Kế Toán',
                'status' => 'active',
                'deadline' => now()->addDays(168),
                'is_deleted' => false,
            ],
            [
                'job_id' => 'JOB_023',
                'title' => 'Social Media Executive',
                'recruitment_period_id' => 'RP_004',
                'description' => 'Quản lý kênh social, lên lịch nội dung và tối ưu tương tác thương hiệu.',
                'requirements' => 'Social media planning, content writing, basic design',
                'salary_min' => 10000000,
                'salary_max' => 16000000,
                'quantity' => 1,
                'location' => 'TP. Hồ Chí Minh',
                'department' => 'Phòng Marketing',
                'status' => 'active',
                'deadline' => now()->addDays(172),
                'is_deleted' => false,
            ],
        ];

        foreach ($jobs as $job) {
            JobPosting::updateOrCreate(
                ['job_id' => $job['job_id']],
                $job
            );
        }
    }
}